apiVersion: v1
kind: Service
metadata:
  name: ai-behavior-service
  labels:
    app: ai-behavior-service
spec:
  type: ClusterIP
  selector:
    app: ai-behavior-service
  ports:
    - port: 8020
      targetPort: 8020
      protocol: TCP
