apiVersion: v1
kind: Service
metadata:
  name: comment-rate-service
  labels:
    app: comment-rate-service
spec:
  type: ClusterIP
  selector:
    app: comment-rate-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
