apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: wait-for-api-gateway
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z api-gateway 8000; do echo waiting for api-gateway; sleep 2; done']
      containers:
      - name: nginx
        image: dunguyenquy/nginx-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "100m"
