apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
      - name: wait-for-postgres-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres-db 5432; do echo waiting for postgres-db; sleep 2; done']
      containers:
      - name: product-service
        image: dunguyenquy/product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: "product_db"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_PORT
          value: "5432"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 6
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "256Mi"
            cpu: "300m"
