apiVersion: v1
kind: Service
metadata:
  name: recommender-ai-service
  labels:
    app: recommender-ai-service
spec:
  type: ClusterIP
  selector:
    app: recommender-ai-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
