# Generated by Django 4.2.29 on 2026-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(default='book', max_length=50),
        ),
    ]
