# Generated by Django 4.2.29 on 2026-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_address_order_payment_method_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(default='book', max_length=50),
        ),
    ]
